spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  level:
    com.studentsystem: DEBUG
