server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.studentsystem.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8

logging:
  level:
    com.studentsystem: debug

jwt:
  secret: student-system-jwt-secret-key-2025-10-22
  expiration: 7200000 # 2 hours in milliseconds
  remember-expiration: 604800000 # 7 days in milliseconds

# Ark AI configuration
ark:
  base-url: https://ark.cn-beijing.volces.com/api/v3
  api-key: 5765d599-bfd9-4d21-a745-b092c80ef580
  model-id: doubao-seed-1-6-251015
