server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.studentsystem.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8

logging:
  level:
    com.studentsystem: DEBUG
# Add these JWT configurations to the existing file
jwt:
  secret: student-system-jwt-secret-key-2025-10-22
  expiration: 7200000 # 2 hours in milliseconds
  remember-expiration: 604800000 # 7 days in milliseconds
